/**
 * ゲーム全体で使用するアクション定数。
 * dispatch({ type: ACTIONS.XXX, payload: {...} }) の形式で利用する。
 * @type {Object.<string, string>}
 */
export const ACTIONS = {
  SET_PHASE: 'SET_PHASE',
  INIT_NEW_GAME: 'INIT_NEW_GAME',
  LOAD_GAME: 'LOAD_GAME',
  START_SESSION: 'START_SESSION',
  TICK_UPDATE: 'TICK_UPDATE',
  END_SESSION: 'END_SESSION',
  OPEN_POSITION: 'OPEN_POSITION',
  CLOSE_POSITION: 'CLOSE_POSITION',
  FORCE_CLOSE_ALL: 'FORCE_CLOSE_ALL',
  UPDATE_UNREALIZED: 'UPDATE_UNREALIZED',
  ADVANCE_DAY: 'ADVANCE_DAY',
  RECORD_DAY: 'RECORD_DAY',
  ADD_EXP: 'ADD_EXP',
  LEVEL_UP: 'LEVEL_UP',
  SET_SPEED: 'SET_SPEED',
  GAME_OVER: 'GAME_OVER',
  BILLIONAIRE: 'BILLIONAIRE',
  ENTER_ENDLESS: 'ENTER_ENDLESS',
}
